### ISSUE TITLE
setup.py reads README.rst, fails when system default encoding is not ansi

### ISSUE THREAD

**Issue by wynick27** [leovp/steamfiles#13]
Here is the error information:
```
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\wy\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.
argv[0] = '"'"'C:\\Users\\wy\\AppData\\Local\\Temp\\pip-req-build-dj1zx2et\\setup.py'"'"'; __file__='"'"'C:\\Users\\wy\\
AppData\\Local\\Temp\\pip-req-build-dj1zx2et\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.r
ead().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base
 pip-egg-info
         cwd: C:\Users\wy\AppData\Local\Temp\pip-req-build-dj1zx2et\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\wy\AppData\Local\Temp\pip-req-build-dj1zx2et\setup.py", line 26, in <module>
        long_description=read('README.rst'),
      File "C:\Users\wy\AppData\Local\Temp\pip-req-build-dj1zx2et\setup.py", line 12, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 2386: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by sakshatshinde** [comment]
### **Steps to reproduce**
`pip install steamfiles`

###**Expected behavior**
Install !

### **Actual behavior**
setup.py", line 12, in
from pip.req import parse_requirements
ImportError: No module named 'pip.req'

### **System configuration**
Python version:
python 3.5
pip 10.0.1

### **Solution**
Seems to be an incompatibility with new version of pip (>=10)
https://stackoverflow.com/a/49867265/1619521

### **Change**
`from pip.req import parse_requirements`

 **to**

```
try: # for pip >= 10
    from pip._internal.req import parse_requirements
except ImportError: # for pip <= 9.0.3
    from pip.req import parse_requirements
```
