### ISSUE TITLE
Unknown VDF_VERSION: 0x07564428

### ISSUE THREAD

**Issue by WinterPhoenix** [leovp/steamfiles#22]
Looks like we have a new VDF_VERSION starting to roll out as part of the Steam Client Beta.

```
>>> with open(r"C:\Users\Winter\Desktop\WIP\appinfo.vdf", "rb") as steamAppInfoFile:
>>>     steamAppInfo = appinfo.load(steamAppInfoFile)
>>>     print(steamAppInfo)
>>>

Traceback (most recent call last):
  File "D:\GModCEFCodecFixDev\steamfiles\steamfiles\debug.py", line 10, in <module>
    steamAppInfo = appinfo.load(steamAppInfoFile)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311_64\Lib\site-packages\steamfiles\appinfo.py", line 29, in load
    return loads(fp.read(), wrapper=wrapper)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311_64\Lib\site-packages\steamfiles\appinfo.py", line 42, in loads
    return AppinfoDecoder(data, wrapper=wrapper).decode()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311_64\Lib\site-packages\steamfiles\appinfo.py", line 102, in decode
    raise ValueError('Unknown VDF_VERSION: 0x{0:08x}'.format(header['version']))
ValueError: Unknown VDF_VERSION: 0x07564428
```
Here's an example `appinfo.vdf` that uses it:
[appinfo_0x07564428.zip](https://github.com/leovp/steamfiles/files/10192606/appinfo_0x07564428.zip)

See also: https://github.com/ValvePython/steam/issues/418, https://github.com/Matoking/protontricks/issues/189

**Comment by luthor112** [comment]
Same problem with 0x07564429.
